name = "iptv-suisse"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = "dist"

[vars]
SITE_URL = "https://iptvsuisse.it.com"
SITE_NAME = "IPTV Suisse"
BRAND_LANGUAGE = "fr-CH"
PRIMARY_KEYWORD = "iptv suisse"
SUPPORT_EMAIL = "support@castvera.com"
CONTACT_EMAIL = "contact@iptvsuisse.it.com"
WHATSAPP_NUMBER = "https://wa.me/18036582620"
WHATSAPP_CHANNEL = "https://whatsapp.com/channel/0029VayVaLpD8SE3bf8wMY3v"
TELEGRAM_CHANNEL = "https://t.me/castvera_com"
